apiVersion: v1
kind: Service
metadata:
  labels:
    app: schevt-mgr
  name: schevt-mgr-svc
spec:
  type: ClusterIP
  ports:
    - name: "80"
      port: 80
      targetPort: 9901
  selector:
    app: schevt-mgr
