---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: schevt-mgr
  name: schevt-mgr
  namespace: schevt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schevt-mgr
  serviceName: "schevtmgr"
  template:
    metadata:
      labels:
        app: schevt-mgr
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - image: hatiolab/schevt-mgr:0.0.1
          imagePullPolicy: Always
          name: schevt-mgr
          resources:
            requests:
              cpu: 256m
              memory: 256Mi
          volumeMounts:
            - name: schevt-storage
              mountPath: /data
            - name: config-volume
              mountPath: /app/config.yaml
              subPath: config.yaml
          securityContext:
            privileged: false
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: config-volume
          configMap:
            name: schevt-mgr-cfgmap
        - name: schevt-storage
          persistentVolumeClaim:
            claimName: efs-schevt-pvc

