# change the file name to 'config.yaml' to be reffered by 

---
masterdb:
  host: abc.com
  port: 1234
  id: username
  pw: likepassword
  db: likedbname
localqueue:
  evt_queue: evt_queue
eventbus:
  type: kafka
  host: localhost:9092
  topic: schevt
  additional: ~